name = "IdeaDrawn"
author = "Greyberet"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92ebe350af03745b07ea7b5a5b2e61d062c59978b1956a81d2638dcf2362873b"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
